name: cloudera-ml-rag-chat-bot

entries:
  - title: Rag Bot!
    label: cml-ft-studio
    short_description: |
        RAG Bot for the CML Docs Domain.
    long_description: |
        TK
    long_description_html: |
        TK
    image_path: >-
      https://github.com/jasonmeverett/cloudera-ml-docs-rag-bot/blob/main/resources/rag-bot.png
    tags:
      - RAG
    git_url: https://github.com/jasonmeverett/cloudera-ml-docs-rag-bot.git
    is_prototype: true
